Added folder structure to asset build folder
H3VR-Modding/MeatKit pull request #17
Opened 2022-05-13 15:54 UTC by cityrobo

Added folder structure to asset build folder so that a build from a different profile doesn't override the old one. profiles create a folder for the build profile and another sub folder for the version of the build mod.

2022-05-13 18:39 UTC, nrgill28 requested changes
I think this is a good change, there's just some small things that need changing.

2022-05-13 18:39 UTC, nrgill28 commented on Assets/MeatKit/Editor/Build.cs
> +            //Debug.Log("Bloop!");
Please remove your debug logs and other commented out stuff

2022-05-13 18:39 UTC, nrgill28 commented on Assets/MeatKit/Editor/Build.cs
> +            BundleOutputPath = Path.Combine(Path.Combine(BundleOutputPathBase, profile.PackageName),profile.Version) + "/";
If you're going to modify this variable, it should be a local variable not a class static one.

2022-05-13 18:39 UTC, nrgill28 commented on Assets/MeatKit/Editor/AssemblyExporter.cs
> +        public static string BundleOutputPath = "AssetBundles/";
Don't need two of these, one should be a `const` (like before) and the other should be a local variable in the DoBuildInternal method instead of a static variable.

2022-05-18 21:48 UTC, cityrobo commented on Assets/MeatKit/Editor/Build.cs
> +            //Debug.Log("Bloop!");
Debug comments have been removed in the last commit.

2022-05-18 21:48 UTC, cityrobo commented on Assets/MeatKit/Editor/Build.cs
> +            BundleOutputPath = Path.Combine(Path.Combine(BundleOutputPathBase, profile.PackageName),profile.Version) + "/";
it's now a local variable.

2022-05-18 21:49 UTC, cityrobo commented on Assets/MeatKit/Editor/AssemblyExporter.cs
> +        public static string BundleOutputPath = "AssetBundles/";
the only `const` variable left is `BundleOutputPathBase`. I had to rename the variable reference in MeatKit.cs to use the new name.

2022-05-19 22:09 UTC, nrgill28 approved these changes

2022-05-19 22:09 UTC, merged